### ISSUE TITLE
[Bug] [Stack trace] RedPajama doesn't work

### ISSUE THREAD

**Issue by GameOverFlowChart** [mlc-ai/binary-mlc-llm-libs#33]
The latest apk (from 5 days ago) crashes while using RedPajama, but llama 2 based models seem to work (I tried the uncensored one). RedPajama gives this error:

```
MLCChat failed

Stack trace:
org.apache.tvm.Base$TVMError: ValueError: Check failed: shard_rec.nbytes == raw_data.length() (29583360 vs. 23663914) : Parameters are not loaded properly. Please check your parameter shards and git lfs installation
Stack trace:
  File "/Users/houbohan/tvm/src/runtime/relax_vm/ndarray_cache_support.cc", line 219

	at org.apache.tvm.Base.checkCall(Base.java:173)
	at org.apache.tvm.Function.invoke(Function.java:130)
	at ai.mlc.mlcllm.ChatModule.reload(ChatModule.java:43)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:636)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:634)
	at ai.mlc.mlcchat.AppViewModel$ChatState.callBackend(AppViewModel.kt:537)
	at ai.mlc.mlcchat.AppViewModel$ChatState.mainReloadChat$lambda$3(AppViewModel.kt:634)
	at ai.mlc.mlcchat.AppViewModel$ChatState.$r8$lambda$JJKpoRMMpp77FzXKA0o00i8lgRA(Unknown Source:0)
	at ai.mlc.mlcchat.AppViewModel$ChatState$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)


Error message:
ValueError: Check failed: shard_rec.nbytes == raw_data.length() (29583360 vs. 23663914) : Parameters are not loaded properly. Please check your parameter shards and git lfs installation
Stack trace:
  File "/Users/houbohan/tvm/src/runtime/relax_vm/ndarray_cache_support.cc", line 219
```

I had RedPajama working on older versions of the apk.

**Comment by GameOverFlowChart** [comment]
I'm not sure if Wizardmath 7b is supposed too work but it also fails

MLCChat failed

```
Stack trace:
org.apache.tvm.Base$TVMError: ValueError: Check failed: shard_rec.nbytes == raw_data.length() (32063488 vs. 17448932) : Parameters are not loaded properly. Please check your parameter shards and git lfs installation
Stack trace:
  File "/Users/houbohan/tvm/src/runtime/relax_vm/ndarray_cache_support.cc", line 219

	at org.apache.tvm.Base.checkCall(Base.java:173)
	at org.apache.tvm.Function.invoke(Function.java:130)
	at ai.mlc.mlcllm.ChatModule.reload(ChatModule.java:43)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:636)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:634)
	at ai.mlc.mlcchat.AppViewModel$ChatState.callBackend(AppViewModel.kt:537)
	at ai.mlc.mlcchat.AppViewModel$ChatState.mainReloadChat$lambda$3(AppViewModel.kt:634)
	at ai.mlc.mlcchat.AppViewModel$ChatState.$r8$lambda$JJKpoRMMpp77FzXKA0o00i8lgRA(Unknown Source:0)
	at ai.mlc.mlcchat.AppViewModel$ChatState$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)


Error message:
ValueError: Check failed: shard_rec.nbytes == raw_data.length() (32063488 vs. 17448932) : Parameters are not loaded properly. Please check your parameter shards and git lfs installation
Stack trace:
  File "/Users/houbohan/tvm/src/runtime/relax_vm/ndarray_cache_support.cc", line 219
```

**Comment by junrushao** [comment]
I think it's pretty indicative of the issue happening here:

> Parameters are not loaded properly. Please check your parameter shards and git lfs installation

It means the full weights are not downloaded properly. It might be network issues you may want to check.

**Comment by GameOverFlowChart** [comment]
> I think it's pretty indicative of the issue happening here:
> 
> > Parameters are not loaded properly. Please check your parameter shards and git lfs installation
> 
> It means the full weights are not downloaded properly. It might be network issues you may want to check.

I will try again and report the outcome.
